let a = 42;
let b = "Bonjour";
let c = true;
let d = null;
let e;
let f = [1, 2, 3];
let g = { nom: "Ali"};
let h = NaN;
console.log("42 ->",typeof(a));
console.log("Bonjour ->",typeof(b));
console.log("true ->",typeof(c));
console.log("null ->",typeof(d));
console.log("undifined ->",typeof(e));
console.log("[1, 2, 3] ->",typeof(f));
console.log("[objet Objet] ->",typeof(g));
console.log("NaN ->",typeof(h));
